language: node_js
node_js:
- "6"
- "8"
script:
- npm run istanbul
- npm run codecov
- npm run codeclimate
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_3e6424b2cd5c_key -iv $encrypted_3e6424b2cd5c_iv
  -in test/serviceAccountCredentials.json.enc -out test/serviceAccountCredentials.json
  -d
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: D+ngIf2kGOUu7t8+VpKRyyYUoLx+UM50Z3Uz8+sP1pIkPUOuTjR3WROJ3/o8n4bcF/9PILu0lPel8THWrMzfNkm9CYw6lpfBbnuHnx2LwZh3LmtQuEHPZKQwXWXZz+7EFhNlDyjVDa5QbLZOrya3WFsI6Vu6/nibaxir8Ngf6GEIzANCw7rLE2yMO8PqxtvSU+A+hMM+i9gvDI9RHSW4BgNsrkPyF8aEfdacB3Rt9smxI25BcMMtIpkPIEcXGAvDso1lHQYS94sRkvuSx7fMa4HX1wrP6OeYhInjlNWI7miqB7ndhf8EMuOruuueWp2b7n6ejQekMcFN6uEigZR/Dwlyzq5QsH+zBCzKcEV/CyY4tLcvScwUDhVV48AMnm8z330+L62DErlwpyR9z8xY3PgTMP7w0ZDb0MvvZtWnN2GWwNnXx4Tjm0di6VzjqIIFlxp0Pg78TYVjMEQ/6hMEKGGnI0kigarneA2TVbTZtrvegA06FpnJuFN5HmGMWRHKOrt56eMUVjyWVUq2O57TGGeeaLYIArMNhCo14En/Ec4jvqZ1l880+/M4+JRFgTSGXl4MIXSJxrm4oVFe9sNoY4YX3XG+C9A30bAHor6C+PCXuEEtyEENU61Dak+l2Ypl/Ku+ohAlNENph9sc60MtSeNLs9+EqYoz3IA+thDK7Qk=
  - secure: b0F83oz2Fo+FKZ86w6j7eJgdpV7cBjTArKyd2tCkdbs9RefQfgvudhcxi1XCImars9amlHndcAqAehvSagAvm7nsqyKqAoroEhGGxD2/fWVmewhH1Z9Nm2YbBtVXXblt5fxy91YOOPlacsNtihMyGM60SPLhabZhUB6kT1p7PTojyIItbblSIQ8a6cHRL2UKCJhb5ckLgs7NmTvW8lHS1SKyYPjywj1vbworGjSpnHIJu1iC4YrIkAqg5rEnNoQFDdxHn7e0r/Zd1MV9E784bj+mQbM6lnMlQI6SQoOhJRF2Jy7sNWSw4SxkcopdaCSELK7OUOmhmbirF0DWgFmTDkk8GCn1N7iNLh7PtzaBeJAJ9mnVj6DMlMkEy2dGmlTsr6FlJSNgqnB2eSOlD5r3Z+Go0ha8MgArQqz8wk/snutY+U/g+SdUHweGn1kZbsmbQd2py0bjjA3HlSVz+cPGLdVjHLvatOlqwkNmLh5P5LPeJWtuYDbrbLsP8x41W1cO19Pv3xJjQOHvoZ86quDT9whI9y5q/i8hcYhmPPpQ2nSSeqpS2SknmdBT5nt/AkTKPQMu2QOdABbvKuuqScUQ2vZcEsYIsPGaI/WilsNFAcDNbPBHfpn1LrT+OAZI77UpDo2FpmEs36RcZ/vjYCFDH5OY6+yOUrdqDikvBwwCmkE=
  - secure: dYlosgaUqru9VtylsIwz2fjHa39jvoH0PA6QzczqrUhgfIqstnn6VrJDw3sEmLgugu12ZUwouB70WcKeMSuqeA0vrfAN4YifiRH2JVkHWOQ/71q3ZU6TbVLOBtFcdSiD9aRerNGwBVSN2nwsnPNLyKLRYbOOUSt+mE+zIMsmvPgXyyVZKWhYJHPi/RSyypP0YoXSA+9vgNFLDjyLWPZn4DQVXssIB5MZjG8+5HueUFp47K/LQJdVhdkVmb2WGiWiju2rJd2WNGSK9yLqBa//j8WfnHEECGYIErNIX423B/J74+Um/7lnLRBZfJDEPr9IRLqAdd4fLyBQIsuAYjSZP0kP9WOPbF6fSTPdEhNvByYOrePmkm4hUMEbkrhnE8kx/yU9Jo1x6UF1+XP37bn4axBxzDBZZcdoFl5P5ITEuJl8ER77M107DuSzps7vqYc42txpGi5l2HK+5zJ2XApGeQlHmXPsACyvlV7M/yTL71poSCI9107DiKGgW5UcIDRlHBaiPNDYaZKGEPG1UeVnwzqxLbfb09W8UeEm1D9+1fxaLlaWV03ZYGSOCy/FO0xeLjhVuuBbUbSfBhgHR/JiZa7SUGE8JeJA33l27c1rKcKEKHwO9Xpfscm1Sox69drcqMCfb4NmxY4L2WgnFrdqNGBXz7OZs0vVmdCnthYP8xo=
